version: "3.2"

networks:
  leportail:

volumes:
  database:

services:
  website:
    build: .
    volumes:
      # apache2 vhosts
      - ./services/apache2/vhost-website.conf:/etc/apache2/sites-available/www.leportail.localhost.conf
      - ./services/apache2/vhost-website.conf:/etc/apache2/sites-enabled/www.leportail.localhost.conf
      - ./services/apache2/vhost-admin.conf:/etc/apache2/sites-available/admin.leportail.localhost.conf
      - ./services/apache2/vhost-admin.conf:/etc/apache2/sites-enabled/admin.leportail.localhost.conf
      # apache2 certificates
      - ./services/apache2/certificates:/etc/apache2/certificates
      # dotclear configuration
      - ./services/website/config.php:/var/www/html/dotclear/inc/config.php
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
    networks:
      - leportail

  mysql:
    image: mysql:5.6.50
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leportaivfgam
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - database:/var/lib/mysql
      - ./backups/development.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306
    networks:
      - leportail
